version: '3.6'
services:
  app:
    depends_on:
      - maria
      - bitcoin
      - liquid
      - lnd
    container_name: app
    image: asoltys/coinos-server
    ports:
      - '3118:3118'
      - '3119:3119'
    environment:
      NODE_ENV: development
    volumes:
      - ./:/app
      - ./logs:/logs
    networks:
      default:
        ipv4_address: 172.18.0.2
  bitcoin:
    image: asoltys/bitcoin:latest
    container_name: bitcoin
    ports:
      - ${BITCOIN_PEER_PORT}:18442
      - ${BITCOIN_NODE_PORT}:18443
    volumes:
      - ./config/bitcoin:/config
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.18.0.3
  liquid:
    image: ghcr.io/vulpemventures/elements
    container_name: liquid
    ports:
      - ${LIQUID_NODE_PORT}:7040
      - ${LIQUID_PEER_PORT}:18444
      - ${LIQUID_BLOCK_PORT}:18606
      - ${LIQUID_TX_PORT}:18607
    volumes:
      - ./config/liquid:/home/elements/.elements
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.18.0.4
  lnd:
    image: lightninglabs/lnd:v0.14.1-beta
    container_name: lnd
    volumes:
      - ./config/lnd:/root/.lnd
      - ./config/bitcoin:/root/.bitcoin
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.18.0.5
  maria:
    container_name: mariadb
    image: mariadb:10.6.1
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${ROOT_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      default:
        ipv4_address: 172.18.0.6
networks: 
  default: 
    external: 
      name: net
