version: '3.6'
services:
  app:
    image: cs
    build: .
    container_name: app
    depends_on:
      - db
    command: "pnpm dev"
    environment:
      NODE_OPTIONS: "--es-module-specifier-resolution=node --experimental-modules --loader ./loader.js"
      NODE_ENV: development
      URL: https://coinos.io
    ports:
      - '3119:3119'
    volumes:
      - ./:/app
      - ./logs:/logs
    restart: always
  db:
    image: eqalpha/keydb
    container_name: db
    volumes:
      - ./data/db:/data
    restart: always
networks:
  default:
    name: net
    external: true
