version: '3.6'
services:
  app:
    image: cs
    container_name: app
    depends_on:
      - rd
      - bc
      - cl
    build: .
    command: "pnpm dev"
    environment:
      NODE_OPTIONS: "--es-module-specifier-resolution=node --experimental-modules --loader ./loader.js"
      NODE_ENV: development
    volumes:
      - ./:/app
      - ./logs:/logs
    restart: always
  bc:
    image: asoltys/bitcoin
    container_name: bc
    volumes:
      - ./config/bitcoin:/home/bitcoin/.bitcoin
    restart: always
  cl:
    image: elementsproject/lightningd:latest
    container_name: cl
    environment:
      LIGHTNINGD_NETWORK: regtest
    volumes:
      - ./config/lightning:/root/.lightning
    restart: always
  rd:
    image: redis
    container_name: rd
    volumes:
      - ./config/redis:/data
    restart: always
  nostr:
    container_name: nostr
    image: asoltys/nostr-rs-relay
    restart: always
    user: 100:100
    volumes:
      - "./config/nostr/data:/usr/src/app/db" 
      - "./config/nostr/config.toml:/usr/src/app/config.toml" 
    ports:
      - '8080:8080'
