version: '3.6'
services:
  app:
    image: cs
    build: .
    container_name: app
    command: "pnpm dev"
    depends_on:
      - db
    environment:
      NODE_ENV: development
      NODE_OPTIONS: "--es-module-specifier-resolution=node --experimental-modules --loader ./loader.js"
      URL: https://coinos.io
    ports:
      - '3119:3119'
    volumes:
      - ./:/app
      - /home/adam/classic-server/config/lightning:/app/data/lightning
      - ./logs:/logs
    restart: always
  db:
    image: eqalpha/keydb
    container_name: db
    volumes:
      - ./data/db:/data
    restart: always
networks:
  default:
    name: net
    external: true
