version: '3.6'
services:
  stapp:
    image: stcs
    build: .
    container_name: stapp
    depends_on:
      - stdb
      - stbc
      - stcl
    command: "pnpm dev"
    environment:
      NODE_OPTIONS: "--es-module-specifier-resolution=node --experimental-modules --loader ./loader.js"
      NODE_ENV: development
      URL: http://localhost:3119
    ports:
      - '3120:3119'
    volumes:
      - ./:/app
      - ./logs:/logs
    restart: always
  stbc:
    image: asoltys/bitcoin
    container_name: stbc
    volumes:
      - ./data/bitcoin:/home/bitcoin/.bitcoin
    restart: always
  stcl:
    image: elementsproject/lightningd:latest
    container_name: stcl
    volumes:
      - ./data/lightning:/root/.lightning
    restart: always
  stdb:
    image: eqalpha/keydb
    container_name: stdb
    volumes:
      - ./data/db:/data
    restart: always
networks:
  default:
    name: net
    external: true
