version: '3.6'
services:
  ui:
    depends_on:
      - app
    container_name: ui
    image: asoltys/coinos-ui:dev
    ports:
      - '8085:8085'
    environment:
      NODE_ENV: development
      # NODE_OPTIONS: --openssl-legacy-provider
    volumes:
      - ../coinos-ui:/app
    networks:
      default:
        ipv4_address: 172.18.0.27
  app:
    depends_on:
      - maria
      - bitcoin
      - liquid
      - lnd
    container_name: app
    image: gcr.io/coinos-326717/github.com/coinos/coinos-server:prod
    ports:
      - '3118:3118'
      - '3119:3119'
    environment:
      NODE_ENV: development
    volumes:
      - ./:/app
      - ./logs:/logs
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      default:
        ipv4_address: 172.18.0.22
  bitcoin:
    image: ghcr.io/vulpemventures/bitcoin
    container_name: bitcoin
    ports:
      - ${BITCOIN_PEER_PORT}:18442
      - ${BITCOIN_NODE_PORT}:18443
    volumes:
      - ./config/bitcoin:/home/bitcoin/.bitcoin
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.18.0.23
  liquid:
    image: ghcr.io/vulpemventures/elements
    container_name: liquid
    ports:
      - ${LIQUID_NODE_PORT}:7040
      - ${LIQUID_PEER_PORT}:18444
      - ${LIQUID_BLOCK_PORT}:18606
      - ${LIQUID_TX_PORT}:18607
    volumes:
      - ./config/liquid:/home/elements/.elements
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.18.0.24
  lnd:
    image: lightninglabs/lnd:v0.15.1-beta
    container_name: lnd
    volumes:
      - ./config/lnd:/root/.lnd
      - ./config/bitcoin:/root/.bitcoin
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.18.0.25
  clightning:
    image: asoltys/lightning
    container_name: cl
    environment:
      LIGHTNINGD_NETWORK: regtest
    volumes:
      - ./config/lightning:/root/.lightning
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.18.0.31
  maria:
    container_name: mariadb
    image: mariadb:10.6.1
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${ROOT_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      default:
        ipv4_address: 172.18.0.26
  electrsb:
    depends_on:
      - bitcoin
    image: ghcr.io/vulpemventures/electrs
    container_name: electrsb
    entrypoint:
      - /build/electrs
    command:
      - -vvvv
      - --network
      - regtest
      - --daemon-dir
      - /config
      - --daemon-rpc-addr
      - bitcoin:18443
      - --cookie
      - admin1:123
      - --http-addr
      - 0.0.0.0:3095
      - --electrum-rpc-addr
      - 0.0.0.0:60400
      - --cors
      - "*"
    volumes:
      - ./config/bitcoin/:/config
    restart: unless-stopped
    ports:
      - 3095:3095
    networks:
      default:
        ipv4_address: 172.18.0.28
  electrs-liquid:
    image: ghcr.io/vulpemventures/electrs-liquid
    container_name: electrs
    depends_on:
      - liquid
    entrypoint:
      - /build/electrs
    command:
      - --jsonrpc-import
      - -vvvv
      - --parent-network
      - regtest
      - --network
      - liquidregtest
      - --daemon-dir
      - /config
      - --daemon-rpc-addr
      - liquid:7040
      - --cookie
      - admin1:123
      - --http-addr
      - 0.0.0.0:3002
      - --electrum-rpc-addr
      - 0.0.0.0:60401
      - --cors
      - "*"
    ports:
      - ${LIQUID_ELECTRS_RPC_PORT}:60401
      - ${LIQUID_ELECTRS_PORT}:3002
    volumes:
      - ./config/liquid/:/config
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.18.0.29
  esplora-liquid:
    image: vulpemventures/esplora:latest
    container_name: esplora-liquid
    depends_on:
      - electrs-liquid
    environment:
      API_URL: ${LIQUID_ELECTRS_URL}
      NATIVE_ASSET_ID: 5ac9f65c0efcc4775e0baec4ec03abdde22473cd3cf33c0419ca290e0751b225
      IS_ELEMENTS: 1
    ports:
      - ${LIQUID_ESPLORA_PORT}:5000
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.18.0.30
networks: 
  default: 
    external: 
      name: net
