version: '3.6'
services:
  caddy:
    container_name: caddy
    image: caddy:2
    restart: always
    ports:
      - "80:80"
    volumes:
      - /var/coinos:/coinos
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy:/data
    environment:
      DOMAIN: "${DOMAIN}"
    networks:
      default:
        ipv4_address: 172.42.0.21
  app:
    container_name: app
    image: gcr.io/coinos-326717/github.com/coinos/coinos-server:prod
    restart: always
    environment:
      NODE_ENV: production
      NODE_OPTIONS: "--es-module-specifier-resolution=node --experimental-modules --loader ./loader.js --openssl-legacy-provider"
    volumes:
      - ./:/app
      - ./logs:/logs
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      default:
        ipv4_address: 172.42.0.22
  maria:
    container_name: maria
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
  bitcoin:
    image: ghcr.io/vulpemventures/bitcoin
    container_name: bitcoin
    volumes:
      - ./config/bitcoin:/home/bitcoin/.bitcoin
    restart: always
    networks:
      default:
        ipv4_address: 172.42.0.23
  liquid:
    image: ghcr.io/vulpemventures/elements
    container_name: liquid
    volumes:
      - ./config/liquid:/home/elements/.elements
    restart: always
    networks:
      default:
        ipv4_address: 172.42.0.24
  cl:
    image: elementsproject/lightningd:v0.12.0
    container_name: cl
    restart: always
    volumes:
      - ./config/lightning:/root/.lightning
    ports:
      - "9735:9735"
    networks:
      default:
        ipv4_address: 172.42.0.25
  lnd:
    image: lightninglabs/lnd:v0.15.1-beta
    container_name: lnd
    volumes:
      - ./config/lnd:/root/.lnd
      - ./config/bitcoin:/root/.bitcoin
    restart: always
    networks:
      default:
        ipv4_address: 172.42.0.26
  tor:
    container_name: tor
    image: dperson/torproxy
    restart: always
    networks:
      default:
        ipv4_address: 172.42.0.27
networks:
  default:
    name: net
    external: true
