version: '3.6'
services:
  app:
    container_name: app
    image: gcr.io/coinos-326717/github.com/coinos/coinos-server:prod
    restart: always
    ports:
      - '3118:3118'
      - '3119:3119'
    environment:
      NODE_ENV: production
      NODE_OPTIONS: "--es-module-specifier-resolution=node --experimental-modules --loader ./loader.js --openssl-legacy-provider"
    volumes:
      - ./:/app
      - ./logs:/logs
      - /root/.lnda/tls.cert:/tls.cert
    extra_hosts:
      - host.docker.internal:host-gateway
  maria:
    container_name: maria
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: pw
networks:
  default:
    name: net
    external: true
